// Generated by gencpp from file topic/U_control_vector.msg
// DO NOT EDIT!


#ifndef TOPIC_MESSAGE_U_CONTROL_VECTOR_H
#define TOPIC_MESSAGE_U_CONTROL_VECTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace topic
{
template <class ContainerAllocator>
struct U_control_vector_
{
  typedef U_control_vector_<ContainerAllocator> Type;

  U_control_vector_()
    : header()
    , u_ControlVector()  {
    }
  U_control_vector_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , u_ControlVector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _u_ControlVector_type;
  _u_ControlVector_type u_ControlVector;





  typedef boost::shared_ptr< ::topic::U_control_vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic::U_control_vector_<ContainerAllocator> const> ConstPtr;

}; // struct U_control_vector_

typedef ::topic::U_control_vector_<std::allocator<void> > U_control_vector;

typedef boost::shared_ptr< ::topic::U_control_vector > U_control_vectorPtr;
typedef boost::shared_ptr< ::topic::U_control_vector const> U_control_vectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic::U_control_vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic::U_control_vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic::U_control_vector_<ContainerAllocator1> & lhs, const ::topic::U_control_vector_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.u_ControlVector == rhs.u_ControlVector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic::U_control_vector_<ContainerAllocator1> & lhs, const ::topic::U_control_vector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topic::U_control_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic::U_control_vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic::U_control_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic::U_control_vector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic::U_control_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic::U_control_vector_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic::U_control_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b7e7f682f6b2c79d3a6cfee564de60e";
  }

  static const char* value(const ::topic::U_control_vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b7e7f682f6b2c79ULL;
  static const uint64_t static_value2 = 0xd3a6cfee564de60eULL;
};

template<class ContainerAllocator>
struct DataType< ::topic::U_control_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic/U_control_vector";
  }

  static const char* value(const ::topic::U_control_vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic::U_control_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[] u_ControlVector\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::topic::U_control_vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic::U_control_vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.u_ControlVector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct U_control_vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic::U_control_vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic::U_control_vector_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "u_ControlVector[]" << std::endl;
    for (size_t i = 0; i < v.u_ControlVector.size(); ++i)
    {
      s << indent << "  u_ControlVector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.u_ControlVector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_MESSAGE_U_CONTROL_VECTOR_H
